apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myservice
  template:
    metadata:
      labels:
        app: myservice
    spec:
      containers:
        - image: sanabns/myservice:1
          imagePullPolicy: IfNotPresent
          name: myservice
          ports:
            - containerPort: 8080
      restartPolicy: Always
